#!/bin/bash

if [[ ! -x $BMOCHA_CHROME ]]; then
  echo "Could not find chrome executable" 1>&2
  echo "Check BMOCHA_CHROME env variable" 1>&2
  exit 1
fi

./node_modules/.bin/bmocha \
  --ssl-key=.certs/key.pem \
  --ssl-cert=.certs/cert.pem \
  --open \
  -m "$BMOCHA_CHROME --allow-insecure-localhost --disable-gpu" \
  "${@}"
